version: '3.9'

services:
  postgres_fast_api:
    image: postgres:13
    container_name: postgres_fast_api
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./postgres_instance/data:/var/lib/postgresql/data
    networks:
      - network_for_fast_api

  fast-api-server:
    build: .
    container_name: fast-api-server
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      postgres_fast_api:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://fast-api-server:8000/v1/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - network_for_fast_api

networks:
  network_for_fast_api:
