"""Create tables in url_shorter schema

Revision ID: ee96d77a60c7
Revises: 
Create Date: 2024-02-04 11:25:55.250802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee96d77a60c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='url_shortener'
    )
    op.create_index(op.f('ix_url_shortener_users_username'), 'users', ['username'], unique=True, schema='url_shortener')
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('short_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['url_shortener.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='url_shortener'
    )
    op.create_index(op.f('ix_url_shortener_urls_key'), 'urls', ['key'], unique=True, schema='url_shortener')
    op.create_index(op.f('ix_url_shortener_urls_secret_key'), 'urls', ['secret_key'], unique=True, schema='url_shortener')
    op.create_index(op.f('ix_url_shortener_urls_short_url'), 'urls', ['short_url'], unique=False, schema='url_shortener')
    op.create_index(op.f('ix_url_shortener_urls_target_url'), 'urls', ['target_url'], unique=False, schema='url_shortener')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_shortener_urls_target_url'), table_name='urls', schema='url_shortener')
    op.drop_index(op.f('ix_url_shortener_urls_short_url'), table_name='urls', schema='url_shortener')
    op.drop_index(op.f('ix_url_shortener_urls_secret_key'), table_name='urls', schema='url_shortener')
    op.drop_index(op.f('ix_url_shortener_urls_key'), table_name='urls', schema='url_shortener')
    op.drop_table('urls', schema='url_shortener')
    op.drop_index(op.f('ix_url_shortener_users_username'), table_name='users', schema='url_shortener')
    op.drop_table('users', schema='url_shortener')
    # ### end Alembic commands ###
